export const PERSONAL_INFO = {
  name: "Johan R. BRAZILLIER",
  initials: "JB",
  title: {
    fr: "Développeur Web & Mobile | Expert React, Next.js, React Native & TypeScript",
    en: "Web & Mobile Developer | Expert React, Next.js, React Native & TypeScript",
    it: "Sviluppatore Web & Mobile | Esperto React, Next.js, React Native & TypeScript",
  },
  email: "j.brazillier@gmail.com",
  phone: "+33 6 38 02 76 49",
  location: "Nice, France",
  available: true,
  social: {
    linkedin: "https://www.linkedin.com/in/johan-r-brazillier",
    github: "https://github.com/brazillierjo",
    portfolio: "https://brazillierjohan.fr",
  },
  cv: {
    fr: "/cv/CV-RINCON-BRAZILLIER-Johan-FR.pdf",
    en: "/cv/CV-RINCON-BRAZILLIER-Johan-EN.pdf",
    it: "/cv/CV-RINCON-BRAZILLIER-Johan-IT.pdf",
  },
  languages: [
    { name: "Français", level: "Natif" },
    { name: "Anglais", level: "Professionnel" },
  ],
} as const;

export const TECH_STACK = {
  frontend: [
    { name: "TypeScript", level: 95 },
    { name: "JavaScript", level: 95 },
    { name: "React", level: 95 },
    { name: "Next.js", level: 95 },
    { name: "Astro", level: 80 },
    { name: "Vue.js", level: 85 },
    { name: "Nuxt", level: 85 },
    { name: "TailwindCSS", level: 95 },
  ],
  mobile: [
    { name: "React Native", level: 90 },
    { name: "Expo", level: 90 },
    { name: "NativeWind", level: 90 },
    { name: "Reanimated", level: 80 },
    { name: "Zustand", level: 85 },
    { name: "TanStack Query", level: 85 },
    { name: "RevenueCat", level: 85 },
    { name: "i18next", level: 85 },
  ],
  backend: [
    { name: "Node.js", level: 85 },
    { name: "Hono", level: 85 },
    { name: "Express", level: 85 },
    { name: "Supabase", level: 85 },
    { name: "Firebase", level: 80 },
    { name: "PostgreSQL", level: 80 },
    { name: "Turso / libSQL", level: 80 },
    { name: "Prisma", level: 85 },
    { name: "Better Auth", level: 75 },
    { name: "Stripe", level: 75 },
    { name: "Python", level: 70 },
    { name: "Docker", level: 75 },
  ],
  tools: [
    "Jest",
    "Vitest",
    "Playwright",
    "Docker",
    "GitHub Actions",
    "Turborepo",
    "EAS Build",
    "Remotion",
    "Google Gemini",
    "OpenAI",
    "Mistral AI",
    "Google Cloud",
    "Figma",
    "Storybook",
    "Sanity",
    "REST API",
    "Sentry",
    "PostHog",
  ],
} as const;

export const SKILL_LEVELS = [
  { name: "TypeScript / JavaScript", level: 95 },
  { name: "React / Next.js", level: 95 },
  { name: "React Native / Expo", level: 90 },
  { name: "Vue.js / Nuxt", level: 85 },
  { name: "Node.js / Hono", level: 85 },
  { name: "Supabase / PostgreSQL", level: 85 },
  { name: "Firebase / Firestore", level: 80 },
  { name: "Gemini / OpenAI / Mistral", level: 85 },
  { name: "Python", level: 70 },
] as const;
